#!/bin/bash

echo "=== GitHub Repository Secrets Setup Guide ==="
echo ""
echo "You need to add the following secrets to your GitHub repository:"
echo "Go to: Settings > Secrets and variables > Actions"
echo ""
echo "Required Secrets:"
echo "=================="
echo ""
echo "1. SLACK_WEBHOOK_URL (Optional - for Slack notifications)"
echo "   - Create Slack app with Incoming Webhooks"
echo "   - Add webhook URL for your channel"
echo ""
echo "2. GITLEAKS_LICENSE (Optional - for enhanced secret scanning)"
echo "   - Get license from https://gitleaks.io/"
echo ""
echo "Environment Variables in Workflows:"
echo "=================================="
echo "- MINIKUBE_VERSION: v1.32.0"
echo "- KUBECTL_VERSION: v1.28.0" 
echo "- HELM_VERSION: v3.13.0"
echo ""
echo "Repository Settings:"
echo "==================="
echo "- Enable Actions in Settings > Actions"
echo "- Set Workflow permissions to 'Read and write permissions'"
echo "- Enable 'Allow GitHub Actions to create and approve pull requests'"
echo ""
echo "Branch Protection (Recommended):"
echo "==============================="
echo "- Require status checks (all CI workflows)"
echo "- Require up-to-date branches"
echo "- Include administrators"