name: Continuous Performance Monitoring

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:
    inputs:
      alert_threshold:
        description: 'Alert threshold for overhead percentage'
        required: false
        default: '75'
        type: string

jobs:
  performance-monitoring:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ALERT_THRESHOLD: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.alert_threshold || '75' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Infrastructure
        run: |
          set -e
          curl -LO https://storage.googleapis.com/minikube/releases/v1.36.0/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          curl -LO "https://dl.k8s.io/release/v1.28.0/bin/linux/amd64/kubectl"
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
          minikube start --driver=docker --memory=4096 --cpus=2 --alsologtostderr -v=7
          
          # Deploy PostgreSQL
          kubectl create namespace database || true
          kubectl apply -f k8s/postgres/
          echo "Waiting for PostgreSQL to be ready..."
          kubectl wait --for=condition=ready pod -l app=postgres -n database --timeout=300s
          
          # Deploy Vault
          kubectl create namespace vault || true
          kubectl apply -f k8s/vault/
          
          # Wait for vault deployment to be available (more reliable than pod-level wait)
          echo "Waiting for vault deployment to be available..."
          kubectl wait --for=condition=available deployment/vault -n vault --timeout=300s || {
            echo "Vault deployment failed to become available, checking status:"
            kubectl get all -n vault
            kubectl describe deployment vault -n vault
            kubectl get pods -n vault
            kubectl describe pods -n vault
            exit 1
          }
          
          # Additional wait for pods to be actually ready (vault might be sealed)
          echo "Waiting for vault pods to be ready..."
          kubectl wait --for=condition=ready pod -l app=vault -n vault --timeout=300s || {
            echo "Vault pods not ready, but continuing (vault might be sealed)..."
            kubectl get pods -n vault
            kubectl logs -n vault -l app=vault --tail=20
          }

      - name: Quick Performance Check
        id: perf_check
        run: |
          set -e
          
          # Verify vault is running before proceeding
          echo "Verifying vault deployment..."
          kubectl get pods -n vault
          
          # Setup Vault with better error handling
          echo "Setting up port forwarding to vault..."
          kubectl port-forward svc/vault-service 8200:8200 -n vault &
          PF_PID=$!
          
          # Wait for port forward to be ready and vault to respond
          echo "Waiting for vault to be accessible..."
          VAULT_READY=false
          for i in {1..30}; do
            if curl -s http://localhost:8200/v1/sys/health >/dev/null 2>&1; then
              echo "Vault is responding"
              VAULT_READY=true
              break
            fi
            echo "Attempt $i/30: Vault not ready yet, waiting..."
            sleep 2
          done
          
          if [ "$VAULT_READY" = "false" ]; then
            echo "Vault not accessible after 60 seconds"
            echo "Checking vault status:"
            kubectl get pods -n vault
            kubectl logs -n vault -l app=vault --tail=50
            kill $PF_PID 2>/dev/null || true
            exit 1
          fi

          export VAULT_ADDR="http://localhost:8200"
          
          # Check if vault is already initialized
          echo "Checking vault initialization status..."
          VAULT_STATUS=$(curl -s http://localhost:8200/v1/sys/init | jq -r '.initialized // false')
          
          if [ "$VAULT_STATUS" = "true" ]; then
            echo "Vault is already initialized, attempting to use existing setup..."
            # Try to use existing root token if available, or skip initialization
            echo "Vault is already initialized. Manual intervention may be needed for unsealing."
            kill $PF_PID 2>/dev/null || true
            exit 1
          fi
          
          # Initialize vault with better error handling
          echo "Initializing vault..."
          vault operator init -key-shares=1 -key-threshold=1 > vault-keys.txt || {
            echo "Vault initialization failed"
            echo "Vault status check:"
            curl -s http://localhost:8200/v1/sys/init || echo "Failed to get vault status"
            cat vault-keys.txt 2>/dev/null || true
            kill $PF_PID 2>/dev/null || true
            exit 1
          }
          
          UNSEAL_KEY=$(grep 'Unseal Key 1:' vault-keys.txt | awk '{print $NF}')
          ROOT_TOKEN=$(grep 'Initial Root Token:' vault-keys.txt | awk '{print $NF}')
          
          echo "Unsealing vault..."
          vault operator unseal $UNSEAL_KEY || {
            echo "Vault unseal failed"
            kill $PF_PID 2>/dev/null || true
            exit 1
          }
          
          echo "Logging into vault..."
          vault login $ROOT_TOKEN || {
            echo "Vault login failed"
            kill $PF_PID 2>/dev/null || true
            exit 1
          }

          # Configure database secrets engine
          echo "Configuring database secrets engine..."
          vault secrets enable database || true
          vault write database/config/postgres \
            plugin_name=postgresql-database-plugin \
            connection_url="postgresql://{{username}}:{{password}}@postgres-service.database.svc.cluster.local:5432/testdb?sslmode=disable" \
            allowed_roles="readonly" \
            username="postgres" \
            password="initialpassword123"

          vault write database/roles/readonly \
            db_name=postgres \
            creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; GRANT SELECT ON ALL TABLES IN SCHEMA public TO \"{{name}}\";" \
            default_ttl="1h" \
            max_ttl="24h"

          # Clean up port forward
          kill $PF_PID 2>/dev/null || true
          
          # Switch to minikube docker environment
          eval $(minikube docker-env)

          # Build apps
          echo "Building applications..."
          BUILD_START=$(date +%s.%N)
          cd test-apps/static-secrets-app && docker build -t static-secrets-app:monitor . && cd ../..
          cd test-apps/vault-secrets-app && docker build -t vault-secrets-app:monitor . && cd ../..
          BUILD_END=$(date +%s.%N)
          BUILD_TIME=$(echo "$BUILD_END - $BUILD_START" | bc -l)

          # Deploy static secrets app
          echo "Deploying static secrets app..."
          STATIC_DEPLOY_START=$(date +%s.%N)
          kubectl apply -f k8s/app/static-secrets-deployment.yaml
          kubectl wait --for=condition=available deployment/static-secrets-app --timeout=300s
          STATIC_DEPLOY_END=$(date +%s.%N)
          STATIC_DEPLOY_TIME=$(echo "$STATIC_DEPLOY_END - $STATIC_DEPLOY_START" | bc -l)

          # Deploy vault secrets app
          echo "Deploying vault secrets app..."
          VAULT_DEPLOY_START=$(date +%s.%N)
          sed "s/REPLACE_WITH_ROOT_TOKEN/$ROOT_TOKEN/g" k8s/app/vault-secrets-deployment.yaml | kubectl apply -f -
          kubectl wait --for=condition=available deployment/vault-secrets-app --timeout=300s
          VAULT_DEPLOY_END=$(date +%s.%N)
          VAULT_DEPLOY_TIME=$(echo "$VAULT_DEPLOY_END - $VAULT_DEPLOY_START" | bc -l)

          # Calculate deployment overhead
          DEPLOY_OVERHEAD=$(echo "$VAULT_DEPLOY_TIME - $STATIC_DEPLOY_TIME" | bc -l)
          DEPLOY_OVERHEAD_PERCENT=$(echo "scale=2; ($DEPLOY_OVERHEAD / $STATIC_DEPLOY_TIME) * 100" | bc -l)

          # Runtime performance test
          echo "Starting runtime performance tests..."
          kubectl port-forward svc/static-secrets-service 8080:5000 &
          STATIC_PID=$!
          kubectl port-forward svc/vault-secrets-service 8081:5000 &
          VAULT_PID=$!
          
          # Wait for services to be ready
          sleep 15

          TOTAL_OVERHEAD=0
          FAILED_TESTS=0

          for i in {1..10}; do
            echo "Running test $i/10..."
            
            STATIC_START=$(date +%s.%N)
            STATIC_RESP=$(curl -s --max-time 10 http://localhost:8080/users || echo "FAILED")
            STATIC_END=$(date +%s.%N)

            VAULT_START=$(date +%s.%N)
            VAULT_RESP=$(curl -s --max-time 10 http://localhost:8081/users || echo "FAILED")
            VAULT_END=$(date +%s.%N)

            if [[ "$STATIC_RESP" == "FAILED" || "$VAULT_RESP" == "FAILED" ]]; then
              echo "Test $i failed"
              FAILED_TESTS=$((FAILED_TESTS + 1))
              continue
            fi

            STATIC_TIME=$(echo "$STATIC_END - $STATIC_START" | bc -l)
            VAULT_TIME=$(echo "$VAULT_END - $VAULT_START" | bc -l)
            OVERHEAD_PERCENT=$(echo "scale=2; (($VAULT_TIME - $STATIC_TIME) / $STATIC_TIME) * 100" | bc -l)
            TOTAL_OVERHEAD=$(echo "$TOTAL_OVERHEAD + $OVERHEAD_PERCENT" | bc -l)
            echo "Test $i overhead: $OVERHEAD_PERCENT%"
          done

          # Clean up port forwards
          kill $STATIC_PID $VAULT_PID 2>/dev/null || true
          
          SUCCESSFUL_TESTS=$((10 - FAILED_TESTS))
          AVG_OVERHEAD=$(echo "scale=2; $SUCCESSFUL_TESTS > 0 ? $TOTAL_OVERHEAD / $SUCCESSFUL_TESTS : 999" | bc -l)

          echo "Performance test completed:"
          echo "- Average overhead: $AVG_OVERHEAD%"
          echo "- Failed tests: $FAILED_TESTS/10"
          echo "- Successful tests: $SUCCESSFUL_TESTS/10"

          # Set outputs
          echo "avg_overhead=$AVG_OVERHEAD" >> $GITHUB_OUTPUT
          echo "failed_tests=$FAILED_TESTS" >> $GITHUB_OUTPUT
          echo "successful_tests=$SUCCESSFUL_TESTS" >> $GITHUB_OUTPUT
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
          echo "static_deploy_time=$STATIC_DEPLOY_TIME" >> $GITHUB_OUTPUT
          echo "vault_deploy_time=$VAULT_DEPLOY_TIME" >> $GITHUB_OUTPUT
          echo "deploy_overhead=$DEPLOY_OVERHEAD" >> $GITHUB_OUTPUT
          echo "deploy_overhead_percent=$DEPLOY_OVERHEAD_PERCENT" >> $GITHUB_OUTPUT
          echo "alert_needed=$(echo "$AVG_OVERHEAD > $ALERT_THRESHOLD" | bc -l)" >> $GITHUB_OUTPUT

      - name: Send Slack Alert if Performance Degraded
        if: ${{ steps.perf_check.outputs.alert_needed == '1' && env.SLACK_WEBHOOK_URL != '' }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{
              "text": ":rotating_light: Vault Performance Alert",
              "blocks": [
                {
                  "type": "header",
                  "text": {"type": "plain_text", "text": "Vault Performance Alert :rotating_light:"}
                },
                {
                  "type": "section",
                  "fields": [
                    {"type": "mrkdwn", "text": "*Runtime Overhead:* ${{ steps.perf_check.outputs.avg_overhead }}%"},
                    {"type": "mrkdwn", "text": "*Deploy Overhead:* ${{ steps.perf_check.outputs.deploy_overhead_percent }}%"},
                    {"type": "mrkdwn", "text": "*Threshold:* ${{ env.ALERT_THRESHOLD }}%"},
                    {"type": "mrkdwn", "text": "*Failed Tests:* ${{ steps.perf_check.outputs.failed_tests }}/10"},
                    {"type": "mrkdwn", "text": "*Build Time:* ${{ steps.perf_check.outputs.build_time }}s"},
                    {"type": "mrkdwn", "text": "*Repository:* ${{ github.repository }}"}
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {"type": "plain_text", "text": "View Workflow"},
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }' $SLACK_WEBHOOK_URL

      - name: Create Performance Issue if Critical
        if: ${{ fromJson(steps.perf_check.outputs.avg_overhead) > 100 }}
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Vault Performance Overhead Exceeded 100%`,
              body: `## Performance Alert Report

              ### Runtime
              - **Average Overhead:** ${{ steps.perf_check.outputs.avg_overhead }}%
              - **Failed Tests:** ${{ steps.perf_check.outputs.failed_tests }}/10

              ### Deployment
              - **Build Time:** ${{ steps.perf_check.outputs.build_time }}s
              - **Static App Deploy Time:** ${{ steps.perf_check.outputs.static_deploy_time }}s
              - **Vault App Deploy Time:** ${{ steps.perf_check.outputs.vault_deploy_time }}s
              - **Deployment Overhead:** ${{ steps.perf_check.outputs.deploy_overhead }}s (${{
              steps.perf_check.outputs.deploy_overhead_percent }}%)

              **Please investigate.**`
            })